[package]
name = "llvm-metal-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
ar = "0.9"
inkwell = { version = "=0.10.0", default-features = false, features = ["llvm22-1-prefer-dynamic"] }
llvm-metal-metallib = { path = "../metallib" }
serde_json = "1"

[dev-dependencies]
llvm-metal-runtime = { path = "../runtime" }
